[tool.poetry]
name = "ml"
version = "0.1.0"
description = ""
authors = ["Da-Woon Kim <wise_head@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
